# Generated by Django 5.2.8 on 2025-12-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_owner_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
