# Generated by Django 5.2.8 on 2026-04-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='alert_100_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='alert_90_sent',
            field=models.BooleanField(default=False),
        ),
    ]
